prod-rackspace-wheezy-2GB:
  - app01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - app02.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - jobs01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - cronjobs
prod-rackspace-wheezy-4GB:
  - reporting01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - elasticsearch
          - kibana
          - app
          - dwh_database
          - dwh_jobs
          - dwh_saiku
  - data01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - queue
          - elasticsearch_data
        solr_role: master
        couchbase_role: master
  - data02.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - elasticsearch_data
        solr_role: slave
  - data03.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - elasticsearch_data
        solr_role: slave
